### PR TITLE
Statically link binary to work on Alpine Linux

### PR DESCRIPTION
**Pull request by lpil**
I've updated the cabal config to produce a statically linked binary so that this bin will work on platforms that don't use libc (such as the popular Alpine Linux)

Here you can see a binary build on ChromeOS being run on Debian and then in an Alpine Linux docker container.

screenshot 2019-03-04 at 13 10 07

Closes https://github.com/stoeffel/elmi-to-json/issues/21

### CODE REVIEW

**Comment by lpil** [comment]
Thank you. Once this has been released I'll try get the node-test-runner team to use this new version.

**Comment by stoeffel** [comment]
@lpil Would you mind trying the binary on your machine, before I release a new version. https://github.com/stoeffel/elmi-to-json/releases/tag/0.19.2

**Comment by lpil** [comment]
ChromeOS Debian container

screenshot 2019-03-05 at 16 29 30

GCP shell Debian and then Alpine Linux

screenshot 2019-03-05 at 16 32 00

Seems good!

**Comment by stoeffel** [comment]
A friend of mine is getting
```
# ~/dev/bin/elmi-to-json                
elmi-to-json: loadlocale.c:129: _nl_intern_locale_data: Assertion `cnt < (sizeof (_nl_value_type_LC_TIME) / sizeof (_nl_value_type_LC_TIME[0]))' failed.
[1]    27808 abort (core dumped)  ~/dev/bin/elmi-to-json
```
seems to be related to my locale. Setting `export LC_ALL=C.UTF-8` and everything works as expected

their locale is
`locale`:
```# locale
LANG=en_GB.UTF-8
LANGUAGE=en_GB:en
LC_CTYPE=en_GB.UTF-8
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER="en_GB.UTF-8"
LC_NAME="en_GB.UTF-8"
LC_ADDRESS="en_GB.UTF-8"
LC_TELEPHONE="en_GB.UTF-8"
LC_MEASUREMENT="en_GB.UTF-8"
LC_IDENTIFICATION="en_GB.UTF-8"
LC_ALL=```

some 1 minute googling brought this up:
https://github.com/hadolint/hadolint/issues/173

seems to be the same error

They are using Ubuntu 18.10 (cc thanks @michaelerne)

Do you think we could build a separate statically linked binary and case on the specific distro in 
https://github.com/stoeffel/elmi-to-json/blob/be1579f22b8746537c9aeea4a129898be4e6b219/index.js#L13-L22?

**Comment by lpil** [comment]
I think we should do whatever Elm format and the Elm compiler does here, their binaries work everywhere.

I've not determined how they manage that though, the Elm compiler project doesn't seem to have made their build scripts public as far as I can see.

The linked issue includes a solution taken from the Stack build tool, perhaps this is the way to go.

**Comment by stoeffel** [comment]
I wonder if we can just drop some of the dependencies to remove the one that has an external dependency.

**Pull request merged**
